site_name: Trilhas de Capacitação
site_description: Portal centralizado das trilhas de conhecimento da Orc’estra.
site_author: Paulo

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - tables

nav:
  - Início: index.md
  - Frontend:
      - Visão Geral: trilha-frontend/index.md
      - Unidade I - Onboarding: trilha-frontend/unidade-1.md
      - Unidade II – HTML & CSS Básico: trilha-frontend/unidade-2.md
      - Unidade III – HTML & CSS Intermediário: trilha-frontend/unidade-3.md
      - Unidade IV – HTML & CSS Avançado: trilha-frontend/unidade-4.md
      - Unidade V – JavaScript: trilha-frontend/unidade-5.md
      - Unidade VI - React: trilha-frontend/unidade-6.md
      - Central de Projetos: trilha-frontend/desafio.md
  - Backend: trilha-backend/index.md
  - DevOps:
      - Módulos de Aprendizado: trilha-devops/index.md
      - Desafios Práticos: trilha-devops/desafio.md
  - Design (Figma):
      - Módulos de Aprendizado: trilha-figma/index.md
      - Desafios Práticos: trilha-figma/desafio.md
  - Gamificação: trilha-gamificacao/index.md
