site_name: Trilhas de Capacitação
site_description: Portal centralizado das trilhas de conhecimento da Orc’estra.
site_author: Paulo

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - tables

nav:
  - Início: index.md
  - Frontend: trilha-frontend/index.md
  - Backend: trilha-backend/index.md
  - DevOps: trilha-devops/index.md
  - Design (Figma):
      - Módulos de Estudo: trilha-figma/index.md
      - Desafio Final: trilha-figma/desafio.md
  - Gamificação: trilha-gamificacao/index.md
